### ISSUE TITLE
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

### ISSUE THREAD

**Issue by Oliverdhonals** [rom1v/sndcpy#151]
The solution of removing -g not working on my Mac 
Any Idea how can I fix it?

Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:621)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:494)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:3104)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1299)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1261)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:186)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.pm.PackageManagerService.onShelUninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]

**Comment by rom1v** [comment]
> The solution of removing -g not working on my Mac

In which file did you remove it?

Refs #39.

**Comment by Oliverdhonals** [comment]
sndcpy.bat

**Comment by rom1v** [comment]
`sndcpy.bat` is for windows, you must modify `sndcpy` (without extension).

**Comment by Oliverdhonals** [comment]
Thanks a lot. It works just fine.
