### ISSUE TITLE
Failed to install sndcpy.apk

### ISSUE THREAD

**Issue by tridaxide** [rom1v/sndcpy#17]
I tried running sndcpy on Windows 10 but what I get is this error:
```
❯ .\sndcpy
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl20906841.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #25)]
Uninstalling existing version first...

Exception occurred while dumping:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4280)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:18294)
        at com.android.server.pm.PackageManagerService.deletePackage(PackageManagerService.java:15670)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:888)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:799)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:118)
        at android.os.ShellCommand.exec(ShellCommand.java:94)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18554)
        at android.os.Binder.shellCommand(Binder.java:468)
        at android.os.Binder.onTransact(Binder.java:367)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2408)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3078)
        at android.os.Binder.execTransact(Binder.java:565)
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl322574919.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #25)]
Failed with error #1.
Press any key to continue . . .
```
I also tried copying the apk to the device and then tried installing from there but the message I got was: **"There was a problem parsing the package."**

**Comment by rom1v** [comment]
sndcpy requires Android 10. Your device use an older version of Android.
