### ISSUE TITLE
problem with Android audio forwarding (sndcpy, but for audio)

### ISSUE THREAD

**Issue by anuragsharma2709** [rom1v/sndcpy#179]
Hi , I am getting Following Error 

Although i have enabled following option on **my android devices**( "Developer Option" is enabled, Along with "USB debugging" and "Install via USB" and "USB Debugging ( Security Setting)"

**Error shown on CMD** 
C:\Users\Amit\Downloads\fresh\sndcpy-with-adb-windows-v1.0>sndcpy.bat
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk:
Exception occurred while executing:
android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
        at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
        at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:422)
        at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:1383)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:201)
        at com.Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4403)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:22845)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:19705)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:745)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:929)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
        at android.os.ShellCommand.exec(ShellCommand.java:96)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23153)
        at android.os.Binder.shellCommand(Binder.java:597)
        at android.os.Binder.onTransact(Binder.java:495)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2671)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3938)
        at android.os.Binder.execTransact(Binder.java:704)
Failed with error #255.
Press any key to continue . . .

C:\Users\Amit\Downloads\fresh\sndcpy-with-adb-windows-v1.0>

**Comment by ShockedCoder** [comment]
I think your phone just ran out of space, so it didn't have enough space to install the sndcpy app.
