### ISSUE TITLE
Failed to install sndcpy.apk

### ISSUE THREAD

**Issue by IanFan21** [rom1v/sndcpy#184]
how to fix this error?  
also when i try install the apk it's show massage "there was a problem parsing the package" 

```
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1230706928.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #28)]
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4364)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21538)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18314)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:743)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21785)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2825)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4058)
        at android.os.Binder.execTransact(Binder.java:731)
Failed with error #255.
```

**Comment by rom1v** [comment]
Requires Android 10.
