### ISSUE TITLE
problem with Android audio forwarding

### ISSUE THREAD

**Issue by Slashtaker** [rom1v/sndcpy#185]
Waiting for device...
Performing Streamed Install
Success

Exception occurred while executing 'set':
java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
        at android.app.ContextImpl.enforce(ContextImpl.java:2073)
        at android.app.ContextImpl.enforcePermission(ContextImpl.java:2082)
        at com.android.server.appop.AppOpsService.enforceManageAppOpsModes(AppOpsService.java:2217)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2490)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2485)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:4783)
        at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:4552)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:4724)
        at android.os.Binder.shellCommand(Binder.java:936)
        at android.os.Binder.onTransact(Binder.java:820)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:1055)
        at android.os.Binder.execTransactInternal(Binder.java:1166)
        at android.os.Binder.execTransact(Binder.java:1130)
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Error type 3
Error: Activity class {com.rom1v.sndcpy/com.rom1v.sndcpy.MainActivity} does not exist.

Waiting for  9993 seconds, press a key to continue ...

**Comment by Practicalbutterfly5** [comment]
Are you using a miui device? 

If so these settings need to be enabled in developer options

1. USB debugging
2. Install via USB
3. USB Debugging (Security Settings)

**Comment by Slashtaker** [comment]
> 

I'am using OppoA92

I use the Wireless debugging to connect the adb
I did't have the "Install via USB" option to enabled it

**Comment by DasniloYT** [comment]
Hey,
I have the same issue here with my Oppo A72

I'm using the wired debugging for adb.
And i also didn't have the "Install via USB" option but i got a "sndcpy" app on my Oppo

**Comment by Practicalbutterfly5** [comment]
For Oppo devices try this

In `Developer options`, scroll to bottom and enable `Disable Permission Monitoring`.

**Comment by Practicalbutterfly5** [comment]
> Hey,
> I have the same issue here with my Oppo A72
> 
> I'm using the wired debugging for adb.
> And i also didn't have the "Install via USB" option but i got a "sndcpy" app on my Oppo

Please share your result if the above solution worked or not, I can't test as I don't own oppo device.

**Comment by DasniloYT** [comment]
@Practicalbutterfly5 it worked for me thanks a lot

**Comment by Practicalbutterfly5** [comment]
> In `Developer options`, scroll to bottom and enable `Disable Permission Monitoring`.
 
@rom1v  I think this should be included in Readme. Same goes for miui security settings for miui devices.
