### ISSUE TITLE
I have some issue with sndcpy, can't get to a solution and there is no issue here till yet for this.

### ISSUE THREAD

**Issue by SupeRBYT** [rom1v/sndcpy#186]

**Comment by SupeRBYT** [comment]
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
Waiting for device...
Performing Streamed Install
adb: failed to open sndcpy.apk: Operation not permitted
Uninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]
SupeRB@Rachit-Bansal sndcpy-v1.1 % ./sndcpy
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
Waiting for device...
Performing Streamed Install
adb: failed to open sndcpy.apk: Operation not permitted
Uninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]

**Comment by SupeRBYT** [comment]
This is the error that comes to me, can you please help me?

**Comment by rom1v** [comment]
What is the result of 
```bash
uid
ls -lh
```

**Comment by SupeRBYT** [comment]
can you pls elaborate, i am kinda new to all this

**Comment by SupeRBYT** [comment]
> What is the result of
> 
> ```shell
> uid
> ls -lh
> ```

Hey I typed this in terminal and this came up.

SupeRB@Rachit-Bansal sndcpy-v1.1 % ls -lh
total 208
-rwxr-xr-x@ 1 SupeRB  staff   799B Nov 30 03:43 sndcpy
-rw-r--r--@ 1 SupeRB  staff    93K Nov 30 03:43 sndcpy.apk
-rwxr-xr-x@ 1 SupeRB  staff   1.0K Dec  3 14:41 sndcpy.bat

Hope this is what you were asking for

**Comment by SupeRBYT** [comment]
wait a minute, actually i provided full disk access to use ls -lh. now i am back to 

SupeRB@Rachit-Bansal sndcpy-v1.1 % ./sndcpy
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: 
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:622)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:495)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:3104)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1299)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1261)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:186)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.pm.PackageManagerService.onShelUninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]

**Comment by rom1v** [comment]
https://github.com/rom1v/sndcpy/issues/39#issuecomment-665273787

**Comment by SupeRBYT** [comment]
Btw, this is all in the scrcpy.bat file:

@echo off
if not defined ADB set ADB=adb
if not defined VLC set VLC="C:\Program Files\VideoLAN\VLC\vlc.exe"
if not defined SNDCPY_APK set SNDCPY_APK=sndcpy.apk
if not defined SNDCPY_PORT set SNDCPY_PORT=28200

if not "%1"=="" (
    set serial=-s %1
    echo Waiting for device %1...
) else (
    echo Waiting for device...
)

%ADB% %serial% wait-for-device || goto :error
%ADB% %serial% install -t -r  %SNDCPY_APK% || (
    echo Uninstalling existing version first...
    %ADB% %serial% uninstall com.rom1v.sndcpy || goto :error
    %ADB% %serial% install -t  %SNDCPY_APK% || goto :error
)
%ADB% %serial% shell appops set com.rom1v.sndcpy PROJECT_MEDIA allow
%ADB% %serial% forward tcp:%SNDCPY_PORT% localabstract:sndcpy || goto :error
%ADB% %serial% shell am start com.rom1v.sndcpy/.MainActivity || goto :error

timeout 2

echo Playing audio...
%VLC% -Idummy --demux rawaud --network-caching=0 --play-and-exit tcp://localhost:%SNDCPY_PORT%
goto :EOF

:error
echo Failed with error #%errorlevel%.
pause
exit /b %errorlevel%

**Comment by SupeRBYT** [comment]
> [#39 (comment)](https://github.com/rom1v/sndcpy/issues/39#issuecomment-665273787)

I told you this above no?

**Comment by SupeRBYT** [comment]
I did what you asked to remove -g thing

**Comment by rom1v** [comment]
If you get `INSTALL_GRANT_RUNTIME_PERMISSIONS` then you did not remove `-g` :)
If you're on Linux, it's not in `sndcpy.bat`, but in `sndcpy`.

**Comment by SupeRBYT** [comment]
I am on mac.
![Screenshot 2021-12-03 at 15 09 51](https://user-images.githubusercontent.com/95472341/144580716-6714af17-db7c-4166-82d6-b76722c9b3e0.png)
see it here.

**Comment by SupeRBYT** [comment]
wait wrong screenshot

**Comment by rom1v** [comment]
Yes, same on mac, it's `sndcpy`, not `sndcpy.bat` which is Windows-specific.

**Comment by SupeRBYT** [comment]
Ohh i c, wait lemme try

**Comment by SupeRBYT** [comment]
#!/bin/bash
set -e
ADB=${ADB:-adb}
VLC=${VLC:-vlc}
SNDCPY_APK=${SNDCPY_APK:-sndcpy.apk}
SNDCPY_PORT=${SNDCPY_PORT:-28200}

serial=
if [[ $# -ge 1 ]]
then
    serial="-s $1"
    echo "Waiting for device $1..."
else
    echo 'Waiting for device...'
fi

"$ADB" $serial wait-for-device
"$ADB" $serial install -t -r  "$SNDCPY_APK" ||
{
    echo 'Uninstalling existing version first...'
    "$ADB" $serial uninstall com.rom1v.sndcpy
    "$ADB" $serial install -t  "$SNDCPY_APK"
}

"$ADB" $serial shell appops set com.rom1v.sndcpy PROJECT_MEDIA allow
"$ADB" $serial forward tcp:$SNDCPY_PORT localabstract:sndcpy
"$ADB" $serial shell am start com.rom1v.sndcpy/.MainActivity

sleep 2

echo Playing audio...
"$VLC" -Idummy --demux rawaud --network-caching=0 --play-and-exit tcp://localhost:"$SNDCPY_PORT"
 
 this is now what i have now in sndcpy file. now i try again.

**Comment by SupeRBYT** [comment]
![Screenshot 2021-12-03 at 15 14 41](https://user-images.githubusercontent.com/95472341/144581464-cb1e6016-5038-4073-be77-c379482072e2.png)
See its still the same thing, i edited it with no -g

**Comment by rom1v** [comment]
There is still a `-g` on your screenshot.

Btw, this is not IRC, please do not post one message every minute :D

Do your tests, and post only when you have something relevant. For example `Ohh i c, wait lemme try` is not necessary :smile:

**Comment by SupeRBYT** [comment]
Same issue was there. Now when I tried in a new window, this is the error 
![Screenshot 2021-12-03 at 15 23 05](https://user-images.githubusercontent.com/95472341/144582632-62a21931-0436-447d-893d-e0aff5c1ebe3.png)

:(

**Comment by rom1v** [comment]
https://github.com/rom1v/sndcpy/issues/14#issuecomment-650940462

**Comment by SupeRBYT** [comment]
I used the script in that thread. So here this is. It is all kinda working, idk its like the sound is coming in phone only. I just have to use the usb cable only right? or i also use 3.5mm cable?
'''SupeRB@Rachit-Bansal sndcpy-v1.1 % ./sndcpy
Waiting for device...
Performing Streamed Install
Success
Intall complete
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...

VLC media player 3.0.16 Vetinari (revision 3.0.16-0-g5e70837d8d)
[00007ffdf8408e50] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00007ffdf9d68090] main stream error: connection error: Connection refused
2021-12-03 15:46:57.921 VLC[19398:1066929] Can't find app with identifier com.apple.iTunes
'''

**Comment by SupeRBYT** [comment]
Bump
