### ISSUE TITLE
cannot play audio on PC

### ISSUE THREAD

**Issue by omanbuluatie** [rom1v/sndcpy#204]
D:\Download\sndcpy-with-adb-windows-v1.1>sndcpy
Waiting for device...
Performing Streamed Install
Success

Exception occurred while executing 'set':
java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
        at android.app.ContextImpl.enforce(ContextImpl.java:2072)
        at android.app.ContextImpl.enforcePermission(ContextImpl.java:2081)
        at com.android.server.appop.AppOpsService.enforceManageAppOpsModes(AppOpsService.java:2217)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2490)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2485)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:4792)
        at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:4561)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:4733)
        at android.os.Binder.shellCommand(Binder.java:936)
        at android.os.Binder.onTransact(Binder.java:820)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:1055)
        at android.os.Binder.execTransactInternal(Binder.java:1166)
        at android.os.Binder.execTransact(Binder.java:1130)
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }

Waiting for 0 seconds, press a key to continue ...
Playing audio...

![gambar](https://user-images.githubusercontent.com/7757296/149682666-d45beb31-6fee-44eb-9844-ee5c29e30053.png)

help me please, the audio not start on my laptop

**Comment by hhguuu76tth** [comment]
I got the same error in cmd , but it still plays audio from Some apps. Ex: I can stream youtube audio from phone but Apple Music has no audio on PC. Is this restricted to some apps?

**Comment by TheHighGroundWins** [comment]
Make sure java sdk is working and installed properly, I've had similar problem is other programs that use the java sdk due to problems.
Or try different java versions or whatever one is recommended for use with sndcpy.
