### ISSUE TITLE
security exeption in sndcpy Please help me

### ISSUE THREAD

**Issue by Zymonk** [rom1v/sndcpy#234]
Exception occurred while executing 'set':
java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
        at android.app.ContextImpl.enforce(ContextImpl.java:2186)
        at android.app.ContextImpl.enforcePermission(ContextImpl.java:2195)
        at com.android.server.appop.AppOpsService.enforceManageAppOpsModes(AppOpsService.java:2560)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2829)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2824)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5565)
        at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:5334)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5506)
        at android.os.Binder.shellCommand(Binder.java:970)
        at android.os.Binder.onTransact(Binder.java:854)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:1198)
        at com.android.server.appop.OplusAppOpsService.onTransact(OplusAppOpsService.java:38)
![Screenshot (2)](https://user-images.githubusercontent.com/110368856/182070858-98a5ed86-6e8c-41ae-b6d6-62868d8a0e6f.png)

        at android.os.Binder.execTransactInternal(Binder.java:1226)
        at android.os.Binder.execTransact(Binder.java:1163)

**Comment by unicornflax** [comment]
had same issue.
enable "disable permission monitoring" in developer options. fixed it for me.
you can disable it after installation.

**Comment by huangjiange** [comment]
You can push the apk file to device sdcard directory or some directory else.
The install the apk file with handle operation.
