### ISSUE TITLE
Exception occurred while executing 'set':

### ISSUE THREAD

**Issue by Pulkit-Py** [rom1v/sndcpy#253]
This is the error i recicve

Waiting for device 9TJJ8DDAFUHYVKSW...
Performing Streamed Install
Success

Exception occurred while executing 'set':
java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
	at android.app.ContextImpl.enforce(ContextImpl.java:2073)
	at android.app.ContextImpl.enforcePermission(ContextImpl.java:2082)
	at com.android.server.appop.AppOpsService.enforceManageAppOpsModes(AppOpsService.java:2214)
	at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2487)
	at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2482)
	at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:4822)
	at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:4591)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:4763)
	at android.os.Binder.shellCommand(Binder.java:936)
	at android.os.Binder.onTransact(Binder.java:820)
	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:1055)
	at android.os.Binder.execTransactInternal(Binder.java:1166)
	at android.os.Binder.execTransact(Binder.java:1130)

**Comment by Pulkit-Py** [comment]
Did you find any solution?

**Comment by Speykious** [comment]
See #234, disabling permission monitoring fixes the issue.
(I got the same issue and it fixed it for me as well)
