### ISSUE TITLE
Looks like sndcpy doesn't work with apps that have In-call volume function inside it.

### ISSUE THREAD

**Issue by pqnhan** [rom1v/sndcpy#257]
I've tried with a bunch of apps, 
 I've noticed: if I use a media player right inside the app (like Youtube, VLC, Podcast) everything works fine, with a slight lag (range 1 - 1.5s).
 But if I use video conferencing, video/voice calling, streaming apps (like Discord, Zoom, Hilokal, or even Google Chrome using websites that require microphone,...) it seems to sndcpy inactive.
![](https://i.imgur.com/BUCuu01.png)

I don't know what is the cause here?  Will I be able to stream from those apps from my phone to my Ubuntu?

**Comment by rom1v** [comment]
Only some apps authorize their audio to be captured: https://github.com/rom1v/sndcpy#apps-restrictions

**Comment by pqnhan** [comment]
@rom1v Is there anyway to patch the manifest.xml files of apps directly from Android?

 I mean, if I patch those apps with `android:allowAudioPlaybackCapture="true" `, will `sndcpy` work?

**Comment by pqnhan** [comment]
It seems that forwarding audio with bluetooth pair also doesn't quite work on some apps, for example with Discord I can't hear any sound when I connect my Android phone to my Ubuntu 20.04, but Youtube still does.

**Comment by mansoorbarri** [comment]
> Only some apps authorize their audio to be captured: https://github.com/rom1v/sndcpy#apps-restrictions

i don't really understand this step, what am i doing here?

**Comment by cybr47** [comment]
@pqnhan we both are on the same track. I am also trying to play Discord call audio on my PC. Did you try patching the app? I used apktool but I got this error

Exception in thread "main" java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.util.regex.Matcher.reset(Unknown Source)
        at java.util.regex.Matcher.<init>(Unknown Source)
        at java.util.regex.Pattern.matcher(Unknown Source)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:140)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:78)

**Comment by cybr47** [comment]
> It seems that forwarding audio with bluetooth pair also doesn't quite work on some apps, for example with Discord I can't hear any sound when I connect my Android phone to my Ubuntu 20.04, but Youtube still does.

Were you abe to find any fix?

**Comment by directentis1** [comment]
@cybr47 Hmm, I guess to be able to capture the in-call volume you must have root access on the Android device and you must use virtual loopback to capture the audio streaming and send it via sndcpy or some other application that streams audio from your phone.

**Comment by directentis1** [comment]
#86 Not a new problem, but is there any possible solution? 🤔️

Like this, use for call-recording?
https://github.com/NLLAPPS/ACRPhoneHelper
