### ISSUE TITLE
Waiting for device...

### ISSUE THREAD

**Issue by Mohamed9658** [rom1v/sndcpy#267]
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1789441072.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #28)]
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4626)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:23586)
        at com.android.server.pm.PackageManagerService.deletePackageVersionedImpl(PackageManagerService.java:19852)
        at com.android.server.pm.HwCloneAppController.deletePackageVersioned(HwCloneAppController.java:382)
        at com.android.server.pm.HwPackageManagerServiceEx.deletePackageVersioned(HwPackageManagerServiceEx.java:3868)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:19825)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:763)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1515)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:201)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23851)
        at android.os.Binder.shellCommand(Binder.java:642)
        at android.os.Binder.onTransact(Binder.java:540)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2804)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4476)
        at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:432)
        at android.os.Binder.execTransact(Binder.java:739)
Failed with error #255.
Press any key to continue . . .

**Comment by Mohamed9658** [comment]
the whole problem in the first comment

**Comment by rom1v** [comment]
> INSTALL_FAILED_OLDER_SDK

sndcpy requires at least Android 10.
