### ISSUE TITLE
Can't run in linux

### ISSUE THREAD

**Issue by HusseinDTS** [rom1v/sndcpy#29]
```
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4307)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21714)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18476)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:738)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21957)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2834)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4020)
	at android.os.Binder.execTransact(Binder.java:726)
```

**Comment by rom1v** [comment]
What did you execute exactly? What is the full output in your console?

**Comment by HusseinDTS** [comment]
this is full out put
````
~/sndcpy-1.0$  ./sndcpy
Waiting for device...
Invalid APK file: sndcpy.apk
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4307)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21714)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18476)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:738)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21957)
	at android.os.Binder.shellCommand(Binder.java:629)
	at android.os.Binder.onTransact(Binder.java:527)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2834)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4020)
	at android.os.Binder.execTransact(Binder.java:726)
````

**Comment by rom1v** [comment]
Did you took the `sndcpy.apk` file from the release, or did you build it yourself?

**Comment by HusseinDTS** [comment]
there is no sndcpy.apk . I download it by my own  .when i try to build it  , it shows error below , I don't know i'm trying this in a wrong way or what : 
````
~/sndcpy-1.0$ ./release.sh 
fatal: not a git repository (or any of the parent directories): .git
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
WARNING: The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.0.
Android SDK Build Tools 29.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:compileReleaseJavaWithJavac FAILED
/home/husseindts/sndcpy-1.0/app/src/main/java/com/rom1v/sndcpy/RecordService.java:15: error: cannot find symbol
import android.media.AudioPlaybackCaptureConfiguration;
                    ^
  symbol:   class AudioPlaybackCaptureConfiguration
  location: package android.media
/home/husseindts/sndcpy-1.0/app/src/main/java/com/rom1v/sndcpy/RecordService.java:134: error: cannot find symbol
    private static AudioPlaybackCaptureConfiguration createAudioPlaybackCaptureConfig(MediaProjection mediaProjection) {
                   ^
  symbol:   class AudioPlaybackCaptureConfiguration
  location: class RecordService
/home/husseindts/sndcpy-1.0/app/src/main/java/com/rom1v/sndcpy/RecordService.java:67: error: cannot find symbol
        startForeground(NOTIFICATION_ID, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);
                                                                  ^
  symbol:   variable FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
  location: class ServiceInfo
/home/husseindts/sndcpy-1.0/app/src/main/java/com/rom1v/sndcpy/RecordService.java:135: error: package AudioPlaybackCaptureConfiguration does not exist
        AudioPlaybackCaptureConfiguration.Builder confBuilder = new AudioPlaybackCaptureConfiguration.Builder(mediaProjection);
                                         ^
/home/husseindts/sndcpy-1.0/app/src/main/java/com/rom1v/sndcpy/RecordService.java:135: error: package AudioPlaybackCaptureConfiguration does not exist
        AudioPlaybackCaptureConfiguration.Builder confBuilder = new AudioPlaybackCaptureConfiguration.Builder(mediaProjection);
                                                                                                     ^
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 750ms
9 actionable tasks: 1 executed, 8 up-to-date
cp: cannot stat '../app/build/outputs/apk/release/app-release.apk': No such file or directory
        zip warning: name not matched: sndcpy.apk
  adding: sndcpy (deflated 46%)
  adding: sndcpy.bat (deflated 52%)
`````
if you can tell me how to build it , please tell me. AND I'm android developer and I have all android SDKs

**Comment by rom1v** [comment]
> there is no sndcpy.apk

In the release, there is `sndcpy.apk`: https://github.com/rom1v/sndcpy/releases/download/v1.0/sndcpy-v1.0.zip

> I download it by my own .when i try to build it , it shows error below

(That's the kind of information which is useful in addition to just a stacktrace in an issue)

>     fatal: not a git repository (or any of the parent directories): .git

Oh, it's just that the release script expects to be run from a git repo (so you should `git clone` this repo, not download some source archive).
It should be changed to also support that, but it's not done.

>     WARNING: The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.0.
Android SDK Build Tools 29.0.2 will be used.

Did you modify the `build.gradle`?

`sndcpy` requires Android 10 anyway (the API has been introduced in Android 10), so don't try to build it for older versions, it won't work.

**Comment by HusseinDTS** [comment]
Tnx. But I'm not sure it works or not.because my android is 9 and I can't test it.Thanks again.
