### ISSUE TITLE
Sndcpy keeps crashing every time I run it with Windows 10

### ISSUE THREAD

**Issue by Zarathos1084** [rom1v/sndcpy#30]
Log:
Waiting for device...
Performing Streamed Install
Success
28200
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...
Playing audio...

![Screenshot_20200715-151408_Settings](https://user-images.githubusercontent.com/48977042/87506300-4d32b780-c6ae-11ea-823c-f2bdeb196445.png)

I am currently running this on S8 plus with custom ROM LineageOS 17.1 installed. May I know if this works with custom ROMs and if so, which ones? Scrcpy works perfectly. After pressing Start Now, the app crashes and is displayed in the screenshot. There is nothing else in the log after pressing Enter.

**Comment by rom1v** [comment]
Please post the error in the output of `adb logcat`.

**Comment by Zarathos1084** [comment]
[logcat.txt](https://github.com/rom1v/sndcpy/files/4934951/logcat.txt)

This is the error that you have requested. 

Thank you for taking the time to go through this. I really appreciate it.

**Comment by rom1v** [comment]
```
07-17 09:40:44.246  4110 12967 E APM_AudioPolicyManager: Unable to find audio module for submix, aborting mix 0 registration
07-17 09:40:44.249  4390  9570 W AS.AudioService: Audio policy registration failed for binder android.media.audiopolicy.IAudioPolicyCallback$Stub$Proxy@fe8c087
07-17 09:40:44.249  4390  9570 W AS.AudioService: java.lang.IllegalStateException: Could not connect mix, error: -3
07-17 09:40:44.249  4390  9570 W AS.AudioService: 	at com.android.server.audio.AudioService$AudioPolicyProxy.<init>(AudioService.java:7389)
07-17 09:40:44.249  4390  9570 W AS.AudioService: 	at com.android.server.audio.AudioService.registerAudioPolicy(AudioService.java:6848)
07-17 09:40:44.249  4390  9570 W AS.AudioService: 	at android.media.IAudioService$Stub.onTransact(IAudioService.java:1578)
07-17 09:40:44.249  4390  9570 W AS.AudioService: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
07-17 09:40:44.249  4390  9570 W AS.AudioService: 	at android.os.Binder.execTransact(Binder.java:994)
07-17 09:40:44.250 15837 15837 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-17 09:40:44.253 15837 15837 E AndroidRuntime: FATAL EXCEPTION: main
07-17 09:40:44.253 15837 15837 E AndroidRuntime: Process: com.rom1v.sndcpy, PID: 15837
07-17 09:40:44.253 15837 15837 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.rom1v.sndcpy.RecordService@3676aaa with Intent { act=com.rom1v.sndcpy.RECORD cmp=com.rom1v.sndcpy/.RecordService (has extras) }: java.lang.UnsupportedOperationException: Error: could not register audio policy
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Error: could not register audio policy
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.media.AudioRecord$Builder.buildAudioPlaybackCaptureRecord(AudioRecord.java:661)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.media.AudioRecord$Builder.build(AudioRecord.java:681)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at com.rom1v.sndcpy.RecordService.createAudioRecord(RecordService.java:155)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at com.rom1v.sndcpy.RecordService.startRecording(RecordService.java:159)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at com.rom1v.sndcpy.RecordService.onStartCommand(RecordService.java:86)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
07-17 09:40:44.253 15837 15837 E AndroidRuntime: 	... 8 more
07-17 09:40:44.258 15837 15837 I Process : Sending signal. PID: 15837 SIG: 9
```
It's the same as #4 (so I'm closing as duplicate).

`UnsupportedOperationException` suggests that something is just not implemented in the device system.
