### ISSUE TITLE
Error with APK? Can't install (Windows and redmi note 7)

### ISSUE THREAD

**Issue by oellado** [rom1v/sndcpy#31]
```
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Invalid apk]
Uninstalling existing version first...
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
    at com.android.server.pm.Settings.isOrphaned(Settings.java:4307)
    at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21723)
    at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18460)
    at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:751)
    at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
    at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
    at android.os.ShellCommand.exec(ShellCommand.java:103)
    at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21980)
    at android.os.Binder.shellCommand(Binder.java:634)
    at android.os.Binder.onTransact(Binder.java:532)
    at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2809)
    at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4023)
    at android.os.Binder.execTransact(Binder.java:735)
Failed with error #255.
Press any key to continue . . .
```

**Comment by rom1v** [comment]
https://stackoverflow.com/questions/47239251/install-failed-user-restricted-android-studio-using-redmi-4-device

**Comment by oellado** [comment]
`https://stackoverflow.com/questions/47239251/install-failed-user-restricted-android-studio-using-redmi-4-device`

tried that and I get this when I run sndcpy on the command line:

Waiting for device...
* daemon not running; starting now at tcp:5037
* daemon started successfully

**Comment by rom1v** [comment]
```
adb devices
```

Your device must be detected by adb.

**Comment by fguille94** [comment]
It's giving me an error about newer SDK required (29, current 28).

![image](https://user-images.githubusercontent.com/12054064/93116635-22031f00-f683-11ea-9916-fb457aa1bcc7.png)

Win10
![image](https://user-images.githubusercontent.com/12054064/93117471-883c7180-f684-11ea-98a0-d20367fc4d4a.png)
![image](https://user-images.githubusercontent.com/12054064/93116962-a9509280-f683-11ea-8bff-6692c68016e1.png)

Followed all steps from the stackoverflow thread above and I guess all permissions from my end are as they should.

**Comment by rom1v** [comment]
Your device runs Android 9, sndcpy requires Android 10.

**Comment by fguille94** [comment]
> Your device runs Android 9, sndcpy requires Android 10.

Oh, I hadn't noticed. Got here from Genymobile/scrcpy and thought that kind of requirements would match. My bad, thanks.
