### ISSUE TITLE
Can't install sndcpy

### ISSUE THREAD

**Issue by LorenzoMS** [rom1v/sndcpy#54]
When I try running it, it gives me this error:

Waiting for device...
adb server is out of date.  killing...
* daemon started successfully *
Invalid APK file: sndcpy.apk
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4637)
        at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:26116)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:26122)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:21765)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:1044)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1701)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:206)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26743)
        at android.os.Binder.shellCommand(Binder.java:916)
        at android.os.Binder.onTransact(Binder.java:790)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5433)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5031)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
Invalid APK file: sndcpy.apk
Failed with error #-1.

Thanks for reading this and sorry for bothering.

**Comment by LorenzoMS** [comment]
Used sndcpy without adb and worked.
