### ISSUE TITLE
Invalid Apk File Issue

### ISSUE THREAD

**Issue by abc123yee** [rom1v/sndcpy#73]
When trying to install sndcpy using the .bat file from sndcpy-with-adb-windows-v1.0 shows this error:

C:\Users\dylan>C:\Users\dylan\Desktop\sndcpy-with-adb-windows-v1.0\sndcpy.bat
Waiting for device...
Invalid APK file: sndcpy.apk
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4636)
        at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:26126)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:26132)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:21773)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:1044)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1701)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:206)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26731)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5433)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4994)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Invalid APK file: sndcpy.apk
Failed with error #-1.
Press any key to continue . . .

Installing sndcpy using the .bat file from sndcpy-v1.0 instead throws this error:

C:\Users\dylan>C:\Users\dylan\Desktop\sndcpy-v1.0\sndcpy.bat
Waiting for device...
Invalid APK file: sndcpy.apk
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4636)
        at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:26126)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:26132)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:21773)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:1044)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1701)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:206)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26731)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5433)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4994)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Invalid APK file: sndcpy.apk
Failed with error #-1.
Press any key to continue . . .

Any idea how to fix?
Pc is Windows 10
Phone is a Samsung a50 running Android 10
VLC 32 bit version installed

**Comment by patel-zeel** [comment]
Following steps worked for me.

git clone this project
1. download the zip from [here](https://github.com/rom1v/sndcpy/releases/download/v1.0/sndcpy-with-adb-windows-v1.0.zip)
1. extract and move sndcpy.apk file to the project folder
1. run ./sndcpy file from the project folder while your device is connected.

**Comment by adryzz** [comment]
Not sure if this is the same issue, but i get that sndcpy.apk uses an older or newer SDK and thus can't be installed. (Android 9 Pie, MediaTek Board)

**Comment by rom1v** [comment]
@adryzz It's not the same issue: sndcpy requires Android 10 (it uses an API introduced in Android 10).

**Comment by renz-dev** [comment]
> @adryzz sndcpy requires Android 10 (it uses an API introduced in Android 10).

So it's not possible for Android 9? :(

**Comment by adryzz** [comment]
> > @adryzz sndcpy requires Android 10 (it uses an API introduced in Android 10).
> 
> So it's not possible for Android 9? :(

no, at least not using those APIs
