### ISSUE TITLE
adb: failed to stat sndcpy.apk:

### ISSUE THREAD

**Issue by araby-os** [rom1v/sndcpy#85]
i am use linux but its not runinng its stack in 

```
~/sndcpy# ./sndcpy
Waiting for device...
adb: failed to stat sndcpy.apk: No such file or directory
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4649)
        at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:26256)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:26262)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:21896)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:1049)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1701)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:206)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26883)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5452)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5044)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by rom1v** [comment]
>     adb: failed to stat sndcpy.apk: No such file or directory

Is `sndcpy.apk` in your current directory?

**Comment by GithubUser699** [comment]
@araby-os 

> ~/sndcpy# ./sndcpy
Waiting for device...
adb: failed to stat sndcpy.apk: No such file or directory

So you're currently in ~/sndcpy and are running sndcpy. sndcpy needs the sndcpy.apk file in the current working directory which is defined in the beginning of the sndcpy file

`SNDCPY_APK=${SNDCPY_APK:-sndcpy.apk}`

If the file is **not** in your current directory, you will get  "no such file or directory" (which is why @rom1v asked whether the apk file is in your current path).

Let's say you want to use sndcpy globaly from everywhere on your computer (without to cd into sndcpy's folder), than you could cp / mv the sndcpy and sndcpy.apk file to /usr/bin/ (on Debian. If you don't know your directory, do something like `whereis sudo` which will provide you the location to put it in.)
Now you only need to edit the sndcpy file (e.g. using _nano_) so this

`SNDCPY_APK=${SNDCPY_APK:-sndcpy.apk}`

becomes this

`SNDCPY_APK=${SNDCPY_APK:-/usr/bin/sndcpy.apk}`


After that your error should disappear.
You could also use every other path pointing to sndcpy.apk by editing the very same line.

I hope it helped. If so, please mark it as closed/solved.

**Comment by araby-os** [comment]
I solve by copy sndcpy.apk to directory 
and I am sorry because I forgot to close the issues 
and my English to

**Comment by mrdudehack** [comment]
I have this problem in windows 8.1
