### ISSUE TITLE
Can't install sndcpy.apk on a phone

### ISSUE THREAD

**Issue by HIIMGOOD** [rom1v/sndcpy#9]
My phone is on Android 9, my pc is on Windows 7
Scrcpy woks fine.

I have extracted sndcpy-with-adb-windows-v1.0.zip into a folder and run sndcpy.bat, typed in "sndcpy" and the output was following:

```
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Inva
lid apk]
Uninstalling existing version first...

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4306)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManager
Service.java:21620)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(Pa
ckageManagerService.java:18379)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstal
lerService.java:738)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(Package
ManagerShellCommand.java:1486)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageMan
agerShellCommand.java:193)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageMan
agerService.java:21877)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.ja
va:2809)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManager
Service.java:4021)
        at android.os.Binder.execTransact(Binder.java:731)
Failed with error #255.
```

I'm not very experienced in coding/programming but as far as i can understand it says that sndcpy.apk is invalid. I have tried connecting my phone via usb and wirelessly trough adb but outcome was the exact same in both cases. Also i tried moving sndcpy.apk on my Google Drive so that i could install it on my phone but it says "Error parsing package" or something similar. 
As i've mentioned before i'm not very experienced in coding/programming so i am not able to build the apk using Gradle or in any other way.

**Comment by rom1v** [comment]
Sndcpy requires Android 10. The new playback capture API has been introduced in Android 10.
